# docker-compose.yml

version: "3.9"
services:

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: farahamri/werkstuk_farahamri:0.1
    ports:
      - "80:${PORT}"
    environment:
     - PG_CON=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}
     - PORT
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - db

  db:
   image: postgres:latest
   ports:
    - 5432:5432
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
   volumes:
    - ./db/data/postgres:/var/lib/postgresql/data